# Generated by Django 4.0.1 on 2022-02-02 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=128, verbose_name='организация')),
                ('start', models.DateField(verbose_name='начало работы')),
                ('end', models.DateField(verbose_name='окончание работы')),
                ('position', models.CharField(max_length=64, verbose_name='должность')),
                ('functions', models.TextField(blank=True, verbose_name='обязанности')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.BigIntegerField(max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата Рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('education_types', models.IntegerField(choices=[(1, 'Среднее'), (2, 'Среднее профессиональное'), (3, 'Высшее')], verbose_name='Образование')),
                ('institution', models.CharField(max_length=100, verbose_name='Учебное заведение')),
                ('courses', models.CharField(max_length=100, verbose_name='Курсы')),
                ('info', models.TextField(verbose_name='Дополнительная информация')),
                ('is_draft', models.BooleanField(default='false', verbose_name='Черновик')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerapp.workexperience', verbose_name='Опыт работы')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerapp.worker', verbose_name='Сотрудник')),
            ],
        ),
    ]
